name: ping

on:
  push:
    branches:
      - main

jobs:
  say-hi:
    runs-on: [self-hosted, ephemeral]
    steps:
      - run: echo "ğŸ§ Hello desde el runner Ã©pico Pullbertito"
      - run: echo "test"
